const KEY="mycarplus_web_v3";
const $=id=>document.getElementById(id);
const f={ownerName:$("ownerName"),vehicleType:$("vehicleType"),brand:$("brand"),model:$("model"),year:$("year"),plate:$("plate"),insuranceDate:$("insuranceDate"),kteoDate:$("kteoDate"),currentKm:$("currentKm"),lastServiceKm:$("lastServiceKm"),serviceEveryKm:$("serviceEveryKm"),fuelCost:$("fuelCost"),serviceCost:$("serviceCost"),vehiclePhoto:$("vehiclePhoto"),documentType:$("documentType"),documentFile:$("documentFile")};
let state={ownerName:"",vehicles:[]},editing=null,photo="",docs=[];
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function load(){try{state=JSON.parse(localStorage.getItem(KEY))||state}catch(e){}}
function esc(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(v){return Number(v||0).toFixed(2)}
function emoji(t){return {Αυτοκίνητο:"🚗",Μηχανή:"🏍️",Scooter:"🛵",Van:"🚐",Φορτηγό:"🚚",ATV:"🏎️"}[t]||"🚘"}
function days(d){if(!d)return null;let a=new Date(),b=new Date(d+"T00:00:00");a.setHours(0,0,0,0);return Math.ceil((b-a)/86400000)}
function dateText(label,d){let x=days(d);if(x===null)return{text:`${label}: δεν ορίστηκε`,cls:"warning",soon:false,expired:false};if(x<0)return{text:`${label}: έληξε`,cls:"danger",soon:false,expired:true};if(x===0)return{text:`${label}: σήμερα`,cls:"danger",soon:true,expired:false};if(x<=7)return{text:`${label}: σε ${x} ημέρες`,cls:"warning",soon:true,expired:false};return{text:`${label}: σε ${x} ημέρες`,cls:"good",soon:false,expired:false}}
function service(v){let c=+v.currentKm||0,l=+v.lastServiceKm||0,e=+v.serviceEveryKm||0;if(!c||!l||!e)return{text:"Service: δεν ορίστηκε",cls:"warning",soon:false,expired:false};let n=l+e,left=n-c;if(left<=0)return{text:`Service: τώρα (${n} km)`,cls:"danger",soon:false,expired:true};if(left<=500)return{text:`Service: σε ${left} km`,cls:"warning",soon:true,expired:false};return{text:`Service: σε ${left} km`,cls:"good",soon:false,expired:false}}
function clearForm(){editing=null;photo="";docs=[];["brand","model","year","plate","insuranceDate","kteoDate","currentKm","lastServiceKm","serviceEveryKm","fuelCost","serviceCost"].forEach(k=>f[k].value="");f.vehicleType.value="Αυτοκίνητο";f.vehiclePhoto.value="";f.documentFile.value="";f.documentType.value="Άδεια";$("photoPreview").innerHTML="📷";$("formTitle").textContent="Προσθήκη οχήματος";$("formSubtitle").textContent="Συμπλήρωσε τα στοιχεία."; $("saveVehicleBtn").textContent="Προσθήκη οχήματος";$("cancelEditBtn").classList.add("hidden");renderDocs()}
function renderDash(){let soon=0,exp=0,cost=0;state.vehicles.forEach(v=>{let a=dateText("Ασφάλεια",v.insuranceDate),k=dateText("ΚΤΕΟ",v.kteoDate),s=service(v);if(a.soon||k.soon||s.soon)soon++;if(a.expired||k.expired||s.expired)exp++;cost+=(+v.fuelCost||0)+(+v.serviceCost||0)});$("dashVehicles").textContent=state.vehicles.length;$("dashSoon").textContent=soon;$("dashExpired").textContent=exp;$("dashCosts").textContent="€"+money(cost)}
function renderDocs(){$("documentsPreview").innerHTML=docs.length?docs.map(d=>`<div class="doc"><div><b>${esc(d.type)}</b><br><small>${esc(d.name)}</small></div><div class="doc-actions"><a href="${d.data}" target="_blank">Άνοιγμα</a><button onclick="removeTempDoc('${d.id}')">Διαγραφή</button></div></div>`).join(""):`<div class="empty">Δεν έχουν προστεθεί έγγραφα.</div>`}
function docsHtml(v){let ds=v.documents||[];return `<div class="vdocs"><b>Έγγραφα (${ds.length})</b>${ds.length?ds.map(d=>`<div class="doc"><div><b>${esc(d.type)}</b><br><small>${esc(d.name)}</small></div><div class="doc-actions"><a href="${d.data}" target="_blank">Άνοιγμα</a></div></div>`).join(""):"<br><small>Δεν υπάρχουν έγγραφα.</small>"}</div>`}
function card(v){let a=dateText("Ασφάλεια",v.insuranceDate),k=dateText("ΚΤΕΟ",v.kteoDate),s=service(v),tot=(+v.fuelCost||0)+(+v.serviceCost||0);let ph=v.photo?`<img src="${v.photo}">`:emoji(v.type);return `<article class="vehicle"><div class="vtop"><div class="vphoto">${ph}</div><div><div class="vtitle">${esc(v.brand)} ${esc(v.model)}</div><div class="vmeta">${emoji(v.type)} ${esc(v.type)} • ${esc(v.year)} • ${esc(v.plate)}</div><div class="chips"><span class="chip ${a.cls}">${a.text}</span><span class="chip ${k.cls}">${k.text}</span><span class="chip ${s.cls}">${s.text}</span></div><div class="costs">Καύσιμα: €${money(v.fuelCost)} • Service/άλλα: €${money(v.serviceCost)} • Σύνολο: €${money(tot)}</div>${docsHtml(v)}<div class="actions"><button class="edit" onclick="editVehicle('${v.id}')">Επεξεργασία</button><button class="delete" onclick="deleteVehicle('${v.id}')">Διαγραφή</button></div></div></div></article>`}
function render(){f.ownerName.value=state.ownerName||"";renderDash();let q=$("searchInput").value.toLowerCase().trim();let list=state.vehicles.filter(v=>`${v.brand} ${v.model} ${v.plate} ${v.type} ${v.year}`.toLowerCase().includes(q));$("vehicleCount").textContent=list.length;$("vehiclesList").innerHTML=list.length?list.map(card).join(""):`<div class="empty">${state.vehicles.length?"Δεν βρέθηκε όχημα.":"Δεν έχεις προσθέσει ακόμα όχημα."}</div>`}
function formData(id){return{id,type:f.vehicleType.value,brand:f.brand.value.trim(),model:f.model.value.trim(),year:f.year.value.trim(),plate:f.plate.value.trim().toUpperCase(),insuranceDate:f.insuranceDate.value,kteoDate:f.kteoDate.value,currentKm:f.currentKm.value,lastServiceKm:f.lastServiceKm.value,serviceEveryKm:f.serviceEveryKm.value,fuelCost:f.fuelCost.value,serviceCost:f.serviceCost.value,photo,documents:docs}}
function saveVehicle(){if(!f.brand.value.trim()||!f.model.value.trim()||!f.year.value.trim()||!f.plate.value.trim()){alert("Συμπλήρωσε μάρκα, μοντέλο, έτος και πινακίδα.");return}if(editing){let i=state.vehicles.findIndex(v=>v.id===editing);if(i>-1)state.vehicles[i]=formData(editing)}else state.vehicles.push(formData(Date.now().toString()));try{save()}catch(e){alert("Δεν χωράει άλλο αρχείο στον browser. Δοκίμασε μικρότερα αρχεία.");return}clearForm();render();scrollTo({top:0,behavior:"smooth"})}
function editVehicle(id){let v=state.vehicles.find(x=>x.id===id);if(!v)return;editing=id;photo=v.photo||"";docs=[...(v.documents||[])];f.vehicleType.value=v.type||"Αυτοκίνητο";["brand","model","year","plate","insuranceDate","kteoDate","currentKm","lastServiceKm","serviceEveryKm","fuelCost","serviceCost"].forEach(k=>f[k].value=v[k]||"");$("photoPreview").innerHTML=photo?`<img src="${photo}">`:"📷";$("formTitle").textContent="Επεξεργασία οχήματος";$("formSubtitle").textContent="Άλλαξε τα στοιχεία και πάτα αποθήκευση.";$("saveVehicleBtn").textContent="Αποθήκευση αλλαγών";$("cancelEditBtn").classList.remove("hidden");renderDocs();scrollTo({top:250,behavior:"smooth"})}
function deleteVehicle(id){let v=state.vehicles.find(x=>x.id===id);if(!confirm(`Να διαγραφεί το ${v? v.brand+" "+v.model:"όχημα"};`))return;state.vehicles=state.vehicles.filter(x=>x.id!==id);if(editing===id)clearForm();save();render()}
function removeTempDoc(id){docs=docs.filter(d=>d.id!==id);renderDocs()}
function addDoc(){let file=f.documentFile.files[0];if(!file){alert("Διάλεξε πρώτα αρχείο.");return}if(file.size>900000){alert("Το αρχείο είναι μεγάλο. Προτίμησε μικρότερο.");f.documentFile.value="";return}let r=new FileReader();r.onload=()=>{docs.push({id:Date.now().toString(),type:f.documentType.value,name:file.name,data:r.result});f.documentFile.value="";renderDocs()};r.readAsDataURL(file)}
f.ownerName.addEventListener("input",()=>{state.ownerName=f.ownerName.value;save()});
f.vehiclePhoto.addEventListener("change",e=>{let file=e.target.files[0];if(!file)return;if(file.size>700000){alert("Η φωτογραφία είναι μεγάλη.");f.vehiclePhoto.value="";return}let r=new FileReader();r.onload=()=>{photo=r.result;$("photoPreview").innerHTML=`<img src="${photo}">`};r.readAsDataURL(file)});
$("saveVehicleBtn").addEventListener("click",saveVehicle);$("cancelEditBtn").addEventListener("click",clearForm);$("addDocumentBtn").addEventListener("click",addDoc);$("searchInput").addEventListener("input",render);
load();renderDocs();render();
